// Test-only bindings. Production bindings (DB, ...) come from
// worker-configuration.d.ts, regenerated by `npm run cf-typegen`.
declare namespace Cloudflare {
  interface Env {
    TEST_MIGRATIONS: import("cloudflare:test").D1Migration[];
  }
}
