# scripts/worktree-bootstrap.ps1
#
# Generated by relay context-builder — project-owned, edit freely.
# Source PRD: PRPs/prds/relay-worktree.prd.md
# Invoked by /relay-worktree as: scripts/worktree-bootstrap.ps1 <absolute-worktree-path>
# Timeout: 60 seconds (relay default, D9). $WorktreePath = absolute path to the new worktree.
#
param([Parameter(Mandatory=$true)][string]$WorktreePath)
$ErrorActionPreference = 'Stop'

# TODO: Uncomment and adapt — env-file replication
# Copy gitignored env files from the repo root into the new worktree.
# Copy-Item .env.local (Join-Path $WorktreePath '.env.local')
# Copy-Item .dev.vars  (Join-Path $WorktreePath '.dev.vars')

# TODO: Uncomment and adapt — dependency install
# Run after env files are in place so the install can read them.
# Push-Location $WorktreePath; npm ci; Pop-Location

# TODO: Uncomment and adapt — port allocation
# Derive an offset from the feature slug hash to avoid port collisions.
# $offset = [System.BitConverter]::ToUInt32([System.Security.Cryptography.MD5]::Create().ComputeHash([Text.Encoding]::UTF8.GetBytes($WorktreePath)),0) % 1000
# "PORT=$(3000 + $offset)" | Add-Content (Join-Path $WorktreePath '.env.local')
