#!/usr/bin/env bash
# scripts/worktree-bootstrap.sh
#
# Generated by relay context-builder — project-owned, edit freely.
# Source PRD: PRPs/prds/relay-worktree.prd.md
# Invoked by /relay-worktree as: scripts/worktree-bootstrap.sh <absolute-worktree-path>
# Timeout: 60 seconds (relay default, D9). $1 = absolute path to the new worktree.
#
set -euo pipefail
WORKTREE_PATH="${1:?Usage: worktree-bootstrap.sh <absolute-worktree-path>}"

# TODO: Uncomment and adapt — env-file replication
# Copy gitignored env files from the repo root into the new worktree.
# cp .env.local "${WORKTREE_PATH}/.env.local"
# cp .dev.vars  "${WORKTREE_PATH}/.dev.vars"

# TODO: Uncomment and adapt — dependency install
# Run after env files are in place so the install can read them.
# cd "${WORKTREE_PATH}" && npm ci

# TODO: Uncomment and adapt — port allocation
# Derive an offset from the feature slug hash to avoid port collisions.
# OFFSET=$(( $(echo -n "${WORKTREE_PATH}" | cksum | cut -d' ' -f1) % 1000 ))
# echo "PORT=$(( 3000 + OFFSET ))" >> "${WORKTREE_PATH}/.env.local"
