# scripts/worktree-bootstrap.ps1
#
# Generated by relay context-builder — project-owned, edit freely.
# Invoked by /relay-worktree as: scripts/worktree-bootstrap.ps1 <absolute-worktree-path>
# Timeout: 60 seconds (relay default, D9). $WorktreePath = absolute path to the new worktree.
#
# Windows fallback, used when scripts/worktree-bootstrap.sh is unavailable.
# Kept behaviourally identical to the .sh — see that file for the reasoning
# behind each step; if you change one, change both.
#
param([Parameter(Mandatory = $true)][string]$WorktreePath)
$ErrorActionPreference = 'Stop'

# --- Env-file replication -----------------------------------------------------
# `.dev.vars` is gitignored. Without it `wrangler types --check` drops every
# secret binding and `npm run check` fails for a reason unrelated to the change
# under review. This project has no `.env.local`.
if (Test-Path .dev.vars) {
    Copy-Item .dev.vars (Join-Path $WorktreePath '.dev.vars')
    Write-Output 'bootstrap: copied .dev.vars into the worktree'
}
else {
    Write-Warning 'bootstrap: no .dev.vars at the repo root; the worktree has no secrets'
}

# --- Dependency install -------------------------------------------------------
# node_modules is NOT shared between worktrees. The flags keep this inside the
# 60-second bootstrap timeout on a warm npm cache; if it is killed anyway,
# re-run `npm ci` inside the worktree by hand (idempotent, repairs a partial
# install).
if (Test-Path (Join-Path $WorktreePath 'node_modules')) {
    Write-Output 'bootstrap: node_modules already present; skipping install'
}
else {
    Push-Location $WorktreePath
    try {
        npm ci --prefer-offline --no-audit --no-fund
        if ($LASTEXITCODE -ne 0) { throw "npm ci failed with exit code $LASTEXITCODE" }
        Write-Output 'bootstrap: dependencies installed'
    }
    finally {
        Pop-Location
    }
}

# --- Port allocation ----------------------------------------------------------
# Deliberately not used — one owner (CON-002), one dev server on the fixed port
# in .claude/launch.json, one worktree at a time.
